apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  flexVolume:
    driver: "fstab/cifs"
    fsType: "cifs"
    secretRef:
      name: "cifs-secret"
    options:
      networkPath: "//192.168.0.201/Multimedia"
      mountOptions: "dir_mode=0755,file_mode=0644,noperm"
    readOnly: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: plex
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-09-22T19:21:54Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plex
    app.kubernetes.io/version: v1.24.1.4931-1a38e63c6
    helm.sh/chart: plex-6.0.2
  name: plex
  namespace: default
  resourceVersion: "40411"
  uid: 40b59d68-6e23-4463-856b-0a60e50b14be
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: plex
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: plex
    spec:
      containers:
      - env:
        - name: ALLOWED_NETWORKS
          value: 192.168.0.0/255.255.255.0,10.0.0.0/255.0.0.0
        - name: PLEX_CLAIM
          value: claim-yYuK2JXR9EQxPzjQ7CsJ
        - name: TZ
          value: Europe/Helsinki
        image: ghcr.io/linuxserver/plex:arm64v8-latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 1
        name: plex
        ports:
        - containerPort: 32400
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
        - mountPath: /nas
          name: nas
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - name: data
        persistentVolumeClaim:
          claimName: plex-data
      - name: nas
        persistentVolumeClaim:
          claimName: nas-claim

