apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  flexVolume:
    driver: "fstab/cifs"
    fsType: "cifs"
    secretRef:
      name: "cifs-secret"
    options:
      networkPath: "//192.168.0.201/Multimedia"
      mountOptions: "dir_mode=0755,file_mode=0644,noperm"
    readOnly: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
